.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH man 1  "man " 
.SH NAME
man \- Generate man pages to a directory
.SH SYNOPSIS
\fBman\fR [\fB\-d\fR|\fB\-\-dir\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Generate man pages to a directory
.SH OPTIONS
.TP
\fB\-d\fR, \fB\-\-dir\fR \fI<DIR>\fR [default: man]
Output directory for man pages
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
