.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH validate 1  "validate " 
.SH NAME
validate \- Validate a Lexicon Markdown file without generating output
.SH SYNOPSIS
\fBvalidate\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIINPUT\fR> 
.SH DESCRIPTION
Validate a Lexicon Markdown file without generating output
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIINPUT\fR>
Input Lexicon Markdown file
